<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
// 	 APLICACION
	'Home' => 'Inicio',
	'Congratulations!' => 'Sistema de Registro de Audiencias',
	'You have successfully created your Yii-powered application.' => 'Poder Judicial de la Provincia de Río Negro',
	'Powered by {yii}' => 'Desarrollado en Yii',
	'Developer' => 'Pablo Marcelo Livigni',
	'Powered' => 'Desarrollado con Yii Framework',
	'My Company' => 'Mi Empresa',
	'About' => 'Acerca',
	'Contact' => 'Contacto',
	'Login' => 'Ingresar',
	'Logout' => 'Salir',
	'Are you sure you want to delete this item?' => '¿Está seguro que desea eliminar este elemento?',
    'View' => 'Ver',
	'Create' => 'Crear',
	'Delete' => 'Eliminar',
    'Reset' => 'Resetear',
    'Search' => 'Buscar',
    'Update' => 'Modificar',
    'Update {modelClass}: ' => 'Modificar {modelClass}:',
	'Please fill out the following fields to login:' => 'Por favor, complete los siguientes campos para iniciar sesión:',
	'Username' => 'Usuario',
	'Password' => 'Clave',
	'rememberMe' => 'Recordarme',
	'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrecta.',
	'( Ninguno )' => '( Ninguno )',
	'( Todos )' => '( Todos )',
		
		
// 	 ERRORES
	'Integrity constraint violation (#23503)' => 'Imposible eliminar, existen relaciones definidas para este elemento.',
		
// 	 ADMINISTRACION USUARIOS
	'Administracion de Usuarios' => 'Administración de Usuarios',
	'Create Usuario' => 'Crear Usuario',
	'View Usuario' => 'Ver Usuario',
	'Usuarioid' => 'Id',
	'Usuarionombre' => 'Nombre',
		
		
// 	 AMBITOS
	'Ambito' => 'Ambito',
	'Create Ambito' => 'Crear Ambito',
	'Ambitoid' => 'Id',
	'Ambitodescripcion' => 'Descripción',
		
// 	 TIPOS DE SECTOR
	'Tipo Sectors' => 'Tipos de Sectores',
	'Tiposector' => 'Tipo Sector',
	'Create Tipo Sector' => 'Crear Tipo de Sector',
	'Tiposectorid' => 'Id',
	'Tiposectordescripcion' => 'Descripción',
		
// 	 SECTORES
	'Sectors' => 'Sectores',
	'Sector' => 'Sector',
    'Create Sector' => 'Crear Sector',
	'Sectorid' => 'Id',
	'Sectordescripcion' => 'Descripción',
		
// 	 TIPOS DE SALAS
	'Tipo Salas' => 'Tipos de Salas',
	'Tiposala' => 'Tipo Sala',
	'Create Tipo Sala' => 'Crear Tipo de Sala',
	'Tiposalaid' => 'Id',
	'Tiposaladescripcion' => 'Descripción',
		
// 	 FERIADOS
	'Feriados' => 'Feriados',
	'Create Feriado' => 'Crear Feriado',
	'Feriadoid' => 'Id',
	'Feriadotexto' => 'Descripción',
	'Feriadofecha' => 'Fecha',
		
// 	 SALAS
	'Salas' => 'Salas',
	'Sala' => 'Sala',
	'Create Sala' => 'Crear Sala',
	'Salaid' => 'Id',
	'Saladescripcion' => 'Descripción',
	'Salaactiva' => 'Activa',
		
// 	 SALA RANGOS HORARIOS
	'Sala Rango Horario' => 'Horario de la Sala',
// 	'Sala Rango Horarios' => 'Horarios de las Salas',
	'Sala Rango Horarios' => 'Salas',
	'Rango Horarios' => 'Horarios de las Sala',
	'Create Sala Rango Horario' => 'Crear Rango Horario',
	'Salarangohorarioid' => 'Id',
	'Salarangohorarioregistrodias' => 'Días',
	'Salarangohorarioinicio' => 'Hora Inicio',
	'Salarangohorariofin' => 'Hora Fin',
	'Salarangohorariodiadomingo' => 'Domingo',
	'Salarangohorariodialunes' => 'Lunes',
	'Salarangohorariodiamartes' => 'Martes',
	'Salarangohorariodiamiercoles' => 'Miércoles',
	'Salarangohorariodiajueves' => 'Jueves',
	'Salarangohorariodiaviernes' => 'Viernes',
	'Salarangohorariodiasabado' => 'Sábado',
	'Error validacion sala rango horario' => 'El rango ingresado solapa a otro definido para la sala. Verifique',
		
// 	 ESTADOS
	'Estado' => 'Estado',
	'Create Estado' => 'Crear Estado',
	'Estadoid' => 'Id',
	'Estadodescripcion' => 'Descripción',

// 	 AUDIENCIAS
	'Audiencia' => 'Audiencia',
	'Audiencias Participa' => 'Audiencias que participa',
	'Create Audiencia' => 'Crear Audiencia',
	'Audienciaid' => 'Id',
	'Audienciadescripcion' => 'Descripción',
	'Audienciafecha' => 'Fecha',
	'Audienciahorainicio' => 'Hora Inicio',
	'Audienciahorafin' => 'Hora Fin',
	'Error validacion con fecha actual' => 'La fecha seleccionada no puede ser menor a la actual',
	'Error validacion feriado' => 'La fecha seleccionada se corresponde con un día feriado. Verifique',
	'Error validacion sala no disponible' => 'No hay salas disponibles para los datos solicitados',
	'No hay rango horario disponible para el dia en la sala' => 'No hay rango horario disponible para el día en la sala', 
	'Audienciaregambitoid' => 'Ambito Registró',
	'Audienciaregsectorid' => 'Sector Registró',
	'Audienciaregrhid' => 'Usuario Registró',
	'Audienciaregfecha' => 'Fecha  Registró',
	'Ambito / Sector Registr�' => 'Ambito / Sector Registró',
	'Los participantes: {participantes}' => 'Los participantes: {participantes} no están disponibles para la fecha y horario seleccionado.',
	'El participante: {participantes}' => 'El participante: {participantes} no está disponible para la fecha y horario seleccionado.',
	'Registrado' => 'Registrada',
		
// 	 ANULAR AUDIENCIAS
	'Create Audienciaanulada' => 'Anular Audiencia',
	'View Audienciaanulada' => 'Ver Anulación',
	'Audienciaanuladafecha' => 'Fecha',
	'Audienciaanuladamotivo' => 'Motivo',
	'Audiencia Anuladas' => 'Audiencias',
	'Create Audiencia Anulada' => 'Anular Audiencia',
	'Audienciaanuladaambitoid' => 'Ambito',
	'Audienciaanuladasectorid' => 'Sector',
	'Audienciaanuladarhid' => 'Recurso Humano',
	
		
// 	 PARTICIPANTES DE LA AUDIENCIA
	'Participante' => 'Nombre',
	'Audiencia Participantes' => 'Audiencias',
	'Create Audiencia Participante' => 'Agregar Participante',
	'Audienciaparticipanteid' => 'Id',
	'AudienciaparticipanteDescripcion' => 'Nombre',
	'The combination of Audienciaid and Rhid has already been taken.' => 'La combinación de "Audiencia" y "RH" ya existe. Verifique',
		
// 	 ADVERTENCIAS DE PARTICIPANTES DE LA AUDIENCIA
	'View Audienciapartwarns' => 'Ver Advertencias',
	'Advertencias Participante' => 'Advertencias al Participante',
	'Audienciaparticipanteid' => 'Id',
	'Audienciapartwarnmsgeanterior' => 'Audiencia Anterior',
	'Audienciapartwarnmsgeposterior' => 'Audiencia Posterior',
	'Audiencia Part Warns' => 'Audiencias',
		
// 	 TIPOS DE RECURSOS HUMANOS
	'Tipo Rhs' => 'Tipos de Recursos Humanos',
	'Tiporh' => 'Tipo',
	'Create Tipo Rh' => 'Crear Tipo Recurso Humano',
	'Tiporhid' => 'Id',
	'Tiporhdescripcion' => 'Descripción',
		
// 	 RECURSOS HUMANOS
	'Rhs' => 'Recursos Humanos',
	'Create Rh' => 'Crear Recurso Humano',
	'Rhid' => 'Id',
	'Rhnombre' => 'Nombre',
	'Rhapellido' => 'Apellido',
	'Rhactivo' => 'Activo',
	'Rhparticipante' => 'Participante',
		
// 	 ERRORES
	'The above error occurred while the Web server was processing your request.' => 'Se ha producido un error mientras el servidor Web procesaba su solicitud.',
	'Please contact us if you think this is a server error. Thank you.' => 'Por favor, póngase en contacto con nosotros si usted cree que es un error del servidor. Gracias.',		
];
